remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: ALEXANDER VELASQUEZ
submodulo: PROGRAMACION APLICACIONES MOVILES I
periodo: 2023-2
url_foto: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.aprenderjuntos.cl%2Fconociendo-al-rey-de-la-selva-el-leon%2F&psig=AOvVaw3sEk4iG4lF73MJvkRorpC1&ust=1695400351956000&source=images&cd=vfe&opi=89978449&ved=0CA4QjRxqFwoTCLC6y9GQvIEDFQAAAAAdAAAAABAD
